### PR TITLE
fix(pushnotifications): App Foreground -> Notification not-clickable

### PR DESCRIPTION
**Pull request by schmop**
### Problem:
When the app is in the foreground, or even active in the background, received push notifications are not clickable at the moment.

### Cause:
I debugged it to be a problem in the [`fireNotification`](https://github.com/ionic-team/capacitor-plugins/blob/c884c38cb2d24105e4667e32ffb6bbe59c97b9b4/push-notifications/android/src/main/java/com/capacitorjs/plugins/pushnotifications/PushNotificationsPlugin.java#L242) method. When creating a local copy of the remote notification (which only happens, if the app is running in back- or foreground), the newly created notification is created without `Intend`.
I am no android developer, excuse me, if I am not firm in the lingo.

### Solution
The proposed changes introduce an intend to the local notification that
* opens the app
* sends the notification data
* dismisses the notification as read.

### CODE REVIEW

**Comment by schmop** [comment]
References #1248

**Comment by marcelbloch** [comment]
seems to fix the issue

**Comment by brilliantinsane** [comment]
Will this ever be merged?

**Comment by junekpavel** [comment]
Thanks a lot for saving my day, applied this via [patch-package](https://www.npmjs.com/package/patch-package) and it works like a charm.

**Comment by AntoscencoVladimir** [comment]
Same here ...

**Comment by trinitiwowka** [comment]
Any news?

**Pull request closed without merging**
