### PR TITLE
Upgrade Share Plugin to be compatible with Version SDK 31

### PR DESCRIPTION
**Pull request by jayp0521**
https://github.com/ionic-team/capacitor-plugins/issues/690

### CODE REVIEW

**Comment by jmalfatto** [comment]
any plan for merge to master?

**Review by jcesarmobile — CHANGES_REQUESTED** [review]
Thanks for the PR!

This is planned as part of the Capacitor 4 release.

If you want to contribute, you should create the pull request pointing to the capacitor-4 branch instead of main. 
You'll need to undo the changes on the gradle file as most changes are already done in capacitor-4 branch.

We have set the minSdkVersion to 22, not 23, so you should add some code to handle that Android version too. 
Let me know if you are willing to do those changes, if not I'll create the pull request myself.

**Comment by jcesarmobile** [comment]
I've sent a PR to capacitor-4 branch fixing the issue, so closing this one.

BTW, my pull request uses FLAG_MUTABLE instead of FLAG_INMUTABLE since that's required to get the id of the app used for sharing, using FLAG_INMUTABLE makes the id of the opening app to be empty.

**Comment by maxcodefaster** [comment]
wen capacitor 4

**Pull request closed without merging**
