### PR TITLE
feat(google-maps): Implemented map feature functions (i.e. GeoJSON support)

### PR DESCRIPTION
**Pull request by AE1NS**
This PR adds support (first implementation scoped to geoJson) for map features.

#### addFeatures(type: FeatureType, data: any, idPropertyName: string, styles: FeatureStyles): string[]
```
await map.addFeatures(
    FeatureType.GeoJSON,
    {
        type: 'Feature',
        geometry: GeoJSONData,
        properties: {
            id: 'my-identifier',
        },
    },
    'id',
    {
        ['my-identifier']: {
            strokeColor: '#123456',
            strokeOpacity: 0.8,
            strokeWeight: 1,
            fillColor: '#654321',
            fillOpacity: 0.1,
            geodesic: true,
        }
    }
)
```

#### getFeatureBounds(featureId: string)
`map.getFeatureBounds('my-identifier')`

#### removeFeature(featureId: string)
`map.removeFeature('my-identifier')`

Closes https://github.com/ionic-team/capacitor-plugins/issues/1604

### CODE REVIEW

**Review by theproducer — CHANGES_REQUESTED** [review]
I've added a page in the test app for testing out GeoJSON support, and grabbed a sample object from Google Map's documentation site.  It works on web, but doesnt work on iOS or Android (on Android it hard crashes).  From looking at it briefly it looks like its due a missing `idPropertyName` within the features.

If that's actually the issue I would rework it so that supplying a id property isn't needed, or, have it throw an appropriate error.

**Comment by AE1NS** [comment]
I see. Seems that I only took the case with an id into account, because I only use it with styles :) You are absolutely correct, this should be an optional parameter.

Did you mean that you are going to rework it, or advised me to do so? I would be glad about support.

**Comment by AE1NS** [comment]
I just pushed some more changes to make the _idPropertyName_ and _styles_ parameter optional. Looks good for me in Android. In iOS I just made the code adjustments but I am not able to test it right now. Would be great if you could have another look.

**Comment by AE1NS** [comment]
Well, I think with the commit in August I broke it completely. Should be fixed now.

**Comment by AE1NS** [comment]
Moved https://github.com/ionic-team/capacitor-google-maps/pull/19

**Pull request closed without merging**
