### PR TITLE
fix: remove unnecessary plugin instances

### PR DESCRIPTION
**Pull request by aparajita**
Unless I'm missing something about the Capacitor 3 architecture, it seems to me that this code is creating two instances of `MotionWeb` that will go completely unused on every platform.

### CODE REVIEW

**Comment by dwieeb** [comment]
You're correct. Just run `npm run fmt` to fix up the formatting.

Just a note: this will have to change anyway when https://github.com/ionic-team/capacitor/pull/3748 is merged in.

**Comment by aparajita** [comment]
> Just run npm run fmt to fix up the formatting

That's odd. I ran eslint and it didn't report any errors.

**Comment by dwieeb** [comment]
It was because of a pretter update (unrelated to this PR)

**Comment by aparajita** [comment]
Thanks! 🙏

**Pull request merged**
