### PR TITLE
feat(app): Add canGoBack to backButton event.

### PR DESCRIPTION
**Pull request by lishid**
This PR adds the `canGoBack` (boolean) status to the event object of the `backButton` event on Android.

This status isn't normally accessible from the JS side, but would be very useful if the app uses the browser history stack for handling navigation.

### CODE REVIEW

**Comment by lishid** [comment]
Related: https://github.com/ionic-team/capacitor-plugins/issues/130#issuecomment-778804244

**Comment by lishid** [comment]
Weird, lint seems to have passed on my previous commit just 10 minutes before, and my new commit only adds the auto-generated docs. It also seems to say '@capacitor/text-zoom' so I'm guessing it's just flaky? Is there any way to re-run the lint?

**Comment by lishid** [comment]
Got lint to re-run and clear the PR!

**Comment by lishid** [comment]
@imhoffd Any feedback? I know you guys are probably busy. Hopefully this small patch won't take long.

**Comment by lishid** [comment]
@jcesarmobile @theproducer

**Review by jcesarmobile — APPROVED** [review]
thanks for the PR
I changed the version to 1.0.0 as it refers to the plugin version, not the capacitor version
it's still not 1.0.0, but will be once we release the final plugins

**Pull request merged**
