### PR TITLE
refactor(geolocation): replace getCurrentPosition logic

### PR DESCRIPTION
**Pull request by theproducer**
closes: https://github.com/ionic-team/capacitor-plugins/issues/571

### CODE REVIEW

**Review by jcesarmobile — CHANGES_REQUESTED** [review]
This should be done for `getCurrentPosition` only, not for `watchPosition`. So the timeout should be documented that it doesn't work for `getCurrentPosition` instead of removing the option as it would still be used for `watchPosition` and will continue working on web and iOS.

I sent a pull request in the past that was not merged because we fixed the problem in a non breaking way, you can use it for reference.

https://github.com/ionic-team/capacitor-plugins/pull/582

**Comment by theproducer** [comment]
> This should be done for `getCurrentPosition` only, not for `watchPosition`. So the timeout should be documented that it doesn't work for `getCurrentPosition` instead of removing the option as it would still be used for `watchPosition` and will continue working on web and iOS.
> 
> I sent a pull request in the past that was not merged because we fixed the problem in a non breaking way, you can use it for reference.
> 
> #582

Ah, got it.  Thanks!

**Comment by jcesarmobile** [comment]
getCurrentPosition calls sendLocation in the implementation class, so sendLocation should contain the new code and requestLocationUpdates should only contain the watchPosition code, so you can remove the getCurrentPosition boolean parameter from it

**Review by jcesarmobile — CHANGES_REQUESTED** [review]
the code is crashing because of `fusedLocationClient` being null, it needs to be initialized like this before it's used `fusedLocationClient = LocationServices.getFusedLocationProviderClient(context);`

**Review by jcesarmobile — APPROVED** [review]

**Comment by piotr-cz** [comment]
How about rejecting promise manually after it times out with race condition like [here](https://stackoverflow.com/questions/67924991/navigator-geolocation-getcurrentposition-hangs-on-ios-pwa/67924992#67924992) ?

**Pull request merged**
