### PR TITLE
chore(android): fix local-notification deprecation warning

### PR DESCRIPTION
**Pull request by markemer**
- Replace getParcelableExtra(String) with getParcelableExtra(String, Class<T>)

### CODE REVIEW

**Review by IT-MikeS — CHANGES_REQUESTED** [review]
Could you separate the old call out into its own function and suppress it there

**Comment by markemer** [comment]
> 

Yep - I'll do that on the other one too.

**Review by jcesarmobile — CHANGES_REQUESTED** [review]
Mike meant to move just the `intent.getParcelableExtra(NOTIFICATION_KEY);` line to a new function so only that code is suppressed by  the `@SuppressWarnings("deprecation")`.

**Comment by markemer** [comment]
> Mike meant to move just the `intent.getParcelableExtra(NOTIFICATION_KEY);` line to a new function so only that code is suppressed by the `@SuppressWarnings("deprecation")`.

I know - but isn't this a little cleaner? And we could just pull out the old code when we hit 33 and higher, which will be lord only knows when. I'm cool with just pulling out the stuff to stop the warnings too, if you think that's better.

**Comment by jcesarmobile** [comment]
Since the `@SuppressWarnings("deprecation")` will hide any future deprecations in the whole method, if we put code in there and it gets deprecated we won't notice, so that's why we only put the deprecated code

I think it's also possible to use inline suppress warnings, that might be another option

**Comment by markemer** [comment]
> Since the `@SuppressWarnings("deprecation")` will hide any future deprecations in the whole method, if we put code in there and it gets deprecated we won't notice, so that's why we only put the deprecated code
> 
> I think it's also possible to use inline suppress warnings, that might be another option

That's a good point - that could become a black hole of deprecated calls.

**Comment by markemer** [comment]
Took @jcesarmobile's advice and went with @IT-MikeS's first idea to avoid accidentally hiding deprecations in the future.

**Review by IT-MikeS — APPROVED** [review]

**Review by jcesarmobile — CHANGES_REQUESTED** [review]
There is another deprecation warning that should be handled:
`local-notifications/android/src/main/java/com/capacitorjs/plugins/localnotifications/LocalNotificationsPlugin.java:139: warning: [deprecation] get(String) in BaseBundle has been deprecated
                        extras.put(key, notification.extras.get(key));`

**Comment by markemer** [comment]
> There is another deprecation warning that should be handled: `local-notifications/android/src/main/java/com/capacitorjs/plugins/localnotifications/LocalNotificationsPlugin.java:139: warning: [deprecation] get(String) in BaseBundle has been deprecated extras.put(key, notification.extras.get(key));`

Damn it - I'll open a new one and reference it here.

**Pull request merged**
