### PR TITLE
fix(local-notifications): Add FLAG_MUTABLE to pending intents for SDK 31

### PR DESCRIPTION
**Pull request by jcesarmobile**
closes https://github.com/ionic-team/capacitor-plugins/issues/689

### CODE REVIEW

**Review by IT-MikeS — APPROVED** [review]

**Comment by egeozer** [comment]
How can I integrate this branch "capacitor-4" into my IONIC project? Under dependencies, I have many @capacitor/xx fields. I have tried changing the @capacitor/core and /local-notifications to this url, but it refuses to install with npm install.

**Comment by hanslbua** [comment]
will this be published in the main branch as well, with a new version of local-notification?

**Review by Gugan-raj — COMMENTED** [review]
will you please tell where to find file

**Comment by Gugan-raj** [comment]
will you please tell where to find file

**Pull request merged**
