### PR TITLE
Refresh Token Push Notifications

### PR DESCRIPTION
**Pull request by josuelmm**
Refresh Token Push Notifications

### CODE REVIEW

**Comment by josuelmm** [comment]
Plis check this

**Comment by sasos90** [comment]
Can we finalize this? I think this is a must have feature, to be able to implement some functionalities.

**Comment by mdivya-symplr** [comment]
any update regarding this? Is there any workaround to get refresh token?

**Comment by felix-ulonska** [comment]
@theproducer

This is a issue in our current App. I would love to see this merged!

**Comment by markemer** [comment]
I'm adding the ability to unregister a token in #1498, which will allow you to unregister via the plugin so you can replicate this functionality in typescript, as well as unregistering without re-registering.

**Comment by markemer** [comment]
Superseded by #1498

**Pull request closed without merging**
