### PR TITLE
Fix(local-notifications): adds RTC_WAKEUP if schedule.allowWhileIdle is true

### PR DESCRIPTION
**Pull request by jduds27**
See docs on RTC vs RTC_WAKEUP
https://developer.android.com/reference/android/app/AlarmManager#RTC

This simply updates RTC to RTC_WAKEUP so that the device wakes up when a local notification goes off and allowWhileIdle is true

### CODE REVIEW

**Comment by nijakobius** [comment]
Thanks, will try it :)

> This simply updates RTC to RTC_WAKEUP so that the device wakes up when a local notification goes off and allowWhileIdle is true

Here it states `Make use of allowWhileIdle judiciously, as these notifications can only fire once per 9 minutes, per app.`:
https://capacitorjs.com/docs/apis/local-notifications#doze

Is this true for your fix? If so it doesn't help my case unfortunately, as our app has a timer which might need to trigger every minute or so...

**Comment by jduds27** [comment]
> Thanks, will try it :)
> 
> > This simply updates RTC to RTC_WAKEUP so that the device wakes up when a local notification goes off and allowWhileIdle is true
> 
> Here it states `Make use of allowWhileIdle judiciously, as these notifications can only fire once per 9 minutes, per app.`: https://capacitorjs.com/docs/apis/local-notifications#doze
> 
> Is this true for your fix? If so it doesn't help my case unfortunately, as our app has a timer which might need to trigger every minute or so...

You are correct. From what I understand in the Android Docs is that using allowWhileIdle could be even up to 15 minutes. In our case, our alarms can't be scheduled within 15 minutes of the last. I'm not sure that this will work for your use case. But it's worth a try. You could test it pretty easily by going into into the LocalNotificationManager.java in android studio and updating line 394 to use RTC_WAKEUP. Good luck!

**Review by giralte-ionic — APPROVED** [review]

**Comment by nijakobius** [comment]
> 

Him, 

> > Thanks, will try it :)
> > > This simply updates RTC to RTC_WAKEUP so that the device wakes up when a local notification goes off and allowWhileIdle is true
> > 
> > 
> > Here it states `Make use of allowWhileIdle judiciously, as these notifications can only fire once per 9 minutes, per app.`: https://capacitorjs.com/docs/apis/local-notifications#doze
> > Is this true for your fix? If so it doesn't help my case unfortunately, as our app has a timer which might need to trigger every minute or so...
> 
> You are correct. From what I understand in the Android Docs is that using allowWhileIdle could be even up to 15 minutes. In our case, our alarms can't be scheduled within 15 minutes of the last. I'm not sure that this will work for your use case. But it's worth a try. You could test it pretty easily by going into into the LocalNotificationManager.java in android studio and updating line 394 to use RTC_WAKEUP. Good luck!

Hrm, I applied the two changes (not line 394, but the ones in "Files changed") and my issue still persists unfortunately (exact same behavior) https://github.com/ionic-team/capacitor-plugins/issues/1341

**Comment by jduds27** [comment]
> > You are correct. From what I understand in the Android Docs is that using allowWhileIdle could be even up to 15 minutes. In our case, our alarms can't be scheduled within 15 minutes of the last. I'm not sure that this will work for your use case. But it's worth a try. You could test it pretty easily by going into into the LocalNotificationManager.java in android studio and updating line 394 to use RTC_WAKEUP. Good luck!
> 
> Hrm, I applied the two changes (not line 394, but the ones in "Files changed") and my issue still persists unfortunately (exact same behavior, even of the first time triggering):
> 
> #1341
> 
> @jduds27 if you clone my repo (https://github.com/nijakobius/capacitor-notifications-test) and apply your two code changes, does it actually fix the issue for you?

I pulled your test app. 
I found that when using schedule: {at: time} the notification did not fire.
However when using: 
  Capacitor.Plugins.LocalNotifications.schedule({notifications: [{
    channelId: '1',
    id: 0,
    title: `scheduled_time: ${new Date(Date.now() + 60000)}`,
    body: `actual time: ${new Date(Date.now())}`,
    schedule: {
      on: {
        weekday: 3,
        hour: 11,
        minute: 10,
      }
    },
    allowWhileIdle: true,
    
    It worked. 
    
    I'm not sure why 'at' and 'on' behave so different. I'll look into it a bit more. My app uses the schedule on because we need alarms that fire at the same time every week. And with the RTC_WAKEUP everything is working as expected. I'll let you know if I find out anything more about 'at' vs 'on'. Good luck!
    
As a work around for your issue you could parse the date and use schedule on, then cancel the notification if you do not need it to fire again the next week (obviously not ideal, but could be a workaround until a fix is found for schedule at).

**Comment by jduds27** [comment]
> > You are correct. From what I understand in the Android Docs is that using allowWhileIdle could be even up to 15 minutes. In our case, our alarms can't be scheduled within 15 minutes of the last. I'm not sure that this will work for your use case. But it's worth a try. You could test it pretty easily by going into into the LocalNotificationManager.java in android studio and updating line 394 to use RTC_WAKEUP. Good luck!
> 
> Hrm, I applied the two changes (not line 394, but the ones in "Files changed") and my issue still persists unfortunately (exact same behavior, even of the first time triggering):
> 
> #1341
> 
> @jduds27 if you clone my repo (https://github.com/nijakobius/capacitor-notifications-test) and apply your two code changes, does it actually fix the issue for you?

Can you try adding allowWhileIdle: true inside the schedule object like this:

```    schedule : {
      at: new Date(Date.now() + 15000),
      allowWhileIdle: true
    },
    ```

**Comment by nijakobius** [comment]
> Can you try adding allowWhileIdle: true inside the schedule object like this:
> 
> ```
> schedule : {
>       at: new Date(Date.now() + 15000),
>       allowWhileIdle: true
> } 
> ```
> 
> It seems to be working for me.

I have it in the schedule object. Do you see anything wrong with my code?

```
  Capacitor.Plugins.LocalNotifications.createChannel({
    id: '1',
    name: 'channel_name',
    description: 'channel_description',
    importance : 5,
    visibility: 1,
    vibration: true,
  }).then(() => Capacitor.Plugins.LocalNotifications.schedule({notifications: [{
    channelId: '1',
    id: 0,
    title: 'notification_title',
    body: 'notification_body',
    schedule : {at: new Date(Date.now() + 15000)},
    allowWhileIdle: true,
  }]}));
  ```

https://github.com/nijakobius/capacitor-notifications-test/blob/main/src/index.html

**Comment by nijakobius** [comment]
Oh yh, I had the `allowWhileIdle` in the notification not the schedule object!

It works now and it also works more than once every 9 minutes

<3

**Comment by bradyjreese** [comment]
@theproducer @IT-MikeS @ItsChaceD You guys should really approve this, cause I need this now. Thank you!

**Comment by sethgray26** [comment]
Please merge. This would solve my issues as well.

**Review by theproducer — APPROVED** [review]

**Review by IT-MikeS — APPROVED** [review]

**Comment by jcesarmobile** [comment]
can you click the "Update branch" button next to "This branch is out-of-date with the base branch"?
the branch is protected and we can't merge if the pull request is not up to date with main branch and looks like you didn't check the "allow edits from maintaners" checkbox when you created the pull request, so we can't update the branch ourselves, has to be done by the PR creator.

**Comment by jduds27** [comment]
Done

**Comment by jduds27** [comment]
> can you click the "Update branch" button next to "This branch is out-of-date with the base branch"? the branch is protected and we can't merge if the pull request is not up to date with main branch and looks like you didn't check the "allow edits from maintaners" checkbox when you created the pull request, so we can't update the branch ourselves, has to be done by the PR creator.

Sorry about that, I'll make sure I check that box in the future.

**Review by jcesarmobile — APPROVED** [review]

**Pull request merged**
