### PR TITLE
bugfix(splashscreen) splashscreen not visible in scenes app

### PR DESCRIPTION
**Pull request by joeflateau**
Referenced by #621

### CODE REVIEW

**Comment by jcesarmobile** [comment]
Thanks for the PR!

I get this error on line 131
> Variable used within its own initial value 

Anyway, there is a similar pull request and I'm merging that one since I like it more 
https://github.com/ionic-team/capacitor-plugins/pull/631

**Comment by joeflateau** [comment]
@jcesarmobile thanks! want me to redo my other PR (#622) to find the window the way #631 does?

**Comment by jcesarmobile** [comment]
Thanks for the offering, but I was already working on it.

If you can verify if my pull request fix your issue it would be helpful
https://github.com/ionic-team/capacitor-plugins/pull/729

**Comment by joeflateau** [comment]
@jcesarmobile I ran the app with #631 and #729 fixes installed and the app worked as expected. I had concerns about finding the window by looking at the first scene rather than finding the owner window from the cap web view, so I tried:

- in info.plist, phone scene listed first before carplay, launch the phone scene first
- in info.plist, carplay scene listed first, launch phone scene first
- in info.plist, carplay scene listed first, launch carplay scene first
- in info.plist, phone scene listed first, launch carplay first

All worked as expected, so does seem like there's some internal consistency that the phone scene will be the `first` scene and CarPlay second, but on iPads where you can have your own app side-by-side with itself I think you'd end up with the wrong dimensions if the cap view is not in the first scene. But for my own purposes, these resolve my issues.

**Comment by jcesarmobile** [comment]
If it works for you then I think it's ok.
Once we drop iOS 12 support we might make the default template a scenes app as Xcode does and then more people could face issues, if that happens we will need to revisit.

**Pull request closed without merging**
