### PR TITLE
feat(camera): Support for Samsung Gallery app on pickImages

### PR DESCRIPTION
**Pull request by N0ctural**
Hello,

Fix to correct issue with multiple image selection on samsung devices (https://github.com/ionic-team/capacitor-plugins/issues/704)

closes https://github.com/ionic-team/capacitor-plugins/issues/704

### CODE REVIEW

**Comment by carlpoole** [comment]
I am testing this on my Samsung Galaxy 9+ on Android 10 and the picker that shows encounters similar issues to the issue. Single-tapping an item causes the picker to disappear and go back to the app with an error. I can long-press items to multi-select but it isn't super obvious. If I select a different app in "Browse files in other apps" such as the Gallery, it has the same issue as the picker did before when selecting the native Gallery app. 

Screenshot_20211129-091152_Files

**Comment by N0ctural** [comment]
Yes, you're right @carlpoole.  I made a change on multi-select method to avoid the error "No image picked" if only one picture is selected. It's works fine on a OnePlus with Android 9.

**Comment by dftd** [comment]
@N0ctural Thanks for fixing this! Is the code ready to be used or you are still working on something?
I need the fix asap.

**Comment by carlpoole** [comment]
Thanks for the update, I tested this again and it seems to be working great now. On my device it is asking which gallery app to use and if I pick the Samsung gallery app, I have the option of selecting multiple and returning or just choosing one. 

I checked what you mentioned about permissions being necessary for external storage but if I try to pick an image off an SD card it seemed to work fine without requesting permissions. Were you testing that on a specific version of Android/Samsung gallery app?

**Comment by N0ctural** [comment]
> Thanks for the update, I tested this again and it seems to be working great now. On my device it is asking which gallery app to use and if I pick the Samsung gallery app, I have the option of selecting multiple and returning or just choosing one.
> 
> I checked what you mentioned about permissions being necessary for external storage but if I try to pick an image off an SD card it seemed to work fine without requesting permissions. Were you testing that on a specific version of Android/Samsung gallery app?

Good news !
About the request permission It was on Samsung A10 with Android 9. I use Browserstack to test the fix (maybe It's a specific problem with their platform).

**Comment by carlpoole** [comment]
I think it's related to the Android version. It seems to work fine for Android 10+ but so far my test on Android 9 and below I do get a crash for missing External permission.

**Comment by N0ctural** [comment]
> I think it's related to the Android version. It seems to work fine for Android 10+ but so far my test on Android 9 and below I do get a crash for missing External permission.

It's maybe specific behaviour with android version and samsung device. (No problem with that on OnePlus / Android 9)
I don't know if the good solution is to ask for permission on all android version or add a specific patch with something like : 

if(Build.VERSION.SDK_INT <= 9.0 && Build.BRAND.equals("Samsung")) {                
  // ask for permission
}

Or maybe just add checkpermission in the web part.

**Review by jcesarmobile — APPROVED** [review]

**Comment by jcesarmobile** [comment]
I've added permission prompt/check, but will continue with the image picking even if denied, in that case it will catch the security exception in devices that require the permissions and reject, or return the images in devices that don't require the permissions

**Pull request merged**
