### PR TITLE
fix(camera): make pickLimitedLibraryPhotos return photos

### PR DESCRIPTION
**Pull request by jcesarmobile**
closes https://github.com/ionic-team/capacitor-plugins/issues/1158

Note: On iOS 14 it's not possible to know when the limited image picker is closed as the method with the completion is only available for iOS 15.
So, for being able to return the pictures, it relies on the `PHPhotoLibraryChangeObserver`. But if the users calls `pickLimitedLibraryPhotos` and then doesn't change the selection, `pickLimitedLibraryPhotos` will not reject nor resolve until some change is made on the user's photo gallery in the future.
Not sure if we want that behavior or if it would be better to just return the pictures on iOS 15+ and document that on iOS 14 it returns an empty array?

### CODE REVIEW

**Comment by giralte-ionic** [comment]
I'd recommend the document method for iOS 14

**Review by giralte-ionic — APPROVED** [review]

**Comment by jcesarmobile** [comment]
return the pictures only on iOS 15+ and document that on iOS 14 it returns an empty array?

**Comment by IT-MikeS** [comment]
I agree it's better to resolve but return nothing (empty array) with documentation as to why that happens on iOS 14

**Review by theproducer — APPROVED** [review]
Tested on 15 and 16, works as expected.

**Review by IT-MikeS — APPROVED** [review]

**Pull request merged**
