### PR TITLE
fix(google-maps): correctly apply CapacitorGoogleMapsPoint y value

### PR DESCRIPTION
**Pull request by antarsaha9**
Fix for marker point image coordinate, which is used to change anchor.

closes https://github.com/ionic-team/capacitor-plugins/issues/1812

### CODE REVIEW

**Review by jcesarmobile — APPROVED** [review]
good catch, thanks!

**Comment by christocracy** [comment]
> good catch, thanks!

You’re welcome.

**Comment by jcesarmobile** [comment]
the pull request is previous to your issue, so antarsaha9 caught it first

**Comment by antarsaha9** [comment]
Thanks very much for accepting the merge request.

**Comment by jcesarmobile** [comment]
Yeah, I sent a pull request yesterday fixing that, it’s linked on this issue.

**Comment by christocracy** [comment]
Super.

**Pull request merged**
