### PR TITLE
fix(filesystem): allow copy if from is not parent of to

### PR DESCRIPTION
**Pull request by tachibana-shin**
Preview error:

image

### CODE REVIEW

**Comment by Shin-Tachibana** [comment]
Preview error:

image

**Review by jcesarmobile — CHANGES_REQUESTED** [review]
can you do it in a way that don't require adding external dependencies?

**Comment by Shin-Tachibana** [comment]
I removed the dependencies. Please reconsider this request

**Review by jcesarmobile — APPROVED** [review]
looks good, thanks!

**Pull request merged**
