### PR TITLE
feat(local-notifications): Add weekday scheduling support for Android and iOS

### LINKED ISSUE #129: feat: `weekday` support in LocalNotifications
# Feature Request

## Describe the Feature Request
I'd like to schedule recurring local notifications on Tuesdays and Thursdays at a given hour.

## Platform Support Requested

- Android
- iOS

## Describe Preferred Solution
I'd like to schedule it using the `on` keyword together with a (new) `weekday` (0-6) keyword. 

## Describe Alternatives
I don't see a way around this, as `day` is only 0-30. I could use `every` — but that doesn't let me set the hour of delivery. https://github.com/ionic-team/capacitor/issues/2752 goes into further detail.

## Related Code
```...
schedule: {
  on: {
    hour: 20,
    weekday: 2
  }
},
...
schedule: {
  on: {
    hour: 20,
    weekday: 4
  }
},
```

## Additional Context
- iOS: [DateComponent](https://developer.apple.com/documentation/foundation/datecomponents) has [`weekday`](https://developer.apple.com/documentation/foundation/datecomponents/1780094-weekday), support so it could easily be added in [`LocalNotifications.swift`](https://github.com/ionic-team/capacitor/blob/master/ios/Capacitor/Capacitor/Plugins/LocalNotifications.swift#L276) from what I gather. 
- Android: I don't know Java but it seems in [`LocalNotificationsSchedule.java`](https://github.com/ionic-team/capacitor/blob/master/android/capacitor/src/main/java/com/getcapacitor/plugin/notification/LocalNotificationSchedule.java) we are using [`SimpleDateFormat`](https://github.com/ionic-team/capacitor/blob/master/android/capacitor/src/main/java/com/getcapacitor/plugin/notification/LocalNotificationSchedule.java) which has a [`u` — day number of week](https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html) (1-7) support.

### PR DESCRIPTION
**Pull request by nkalupahana**
Fixes #129!

The past PR that did this (#601) has gone stale, so I figured I'd do it myself and verify it. Weekdays go from 1 (Sunday) to 7 (Saturday), as dictated by both the iOS and Android standards. I've tested this functionality on both iOS and Android and it all seems to work appropriately.

### CODE REVIEW

**Comment by nkalupahana** [comment]
@jcesarmobile linting is fixed; if you could re-approve workflows that would be great :)

**Review by jcesarmobile — CHANGES_REQUESTED** [review]
Can you create an enum for the days, something like this
```
enum Days {
  Sunday = 1,
  Monday,
  Tuesday,
  Wednesday,
  Thursday,
  Friday,
  Saturday
}
```
and assign that enum type to weekday?

That way it's more clear Sunday it's the 1, and also people can use it like `Days.Sunday` instead of using the numbers directly

**Comment by nkalupahana** [comment]
@jcesarmobile all set, let me know if this works

**Review by jcesarmobile — CHANGES_REQUESTED** [review]
Can you add numbers to all days? 

I was hopping the doc generator would be smart enough to generate the missing numbers by incrementing the first one, but looks like it doesn't.

**Comment by nkalupahana** [comment]
@jcesarmobile ✅

**Comment by nkalupahana** [comment]
@jcesarmobile sorry about that, I thought I ran linter but apparently I didn't.

**Review by jcesarmobile — APPROVED** [review]
looks good, I scheduled notifications for all week and left it running over the weekend and everything fired when expected

**Comment by mahen23** [comment]
> 

Hello, i want notifications to run only on weekdays(monday - friday), no weekends. How to i set it ?

**Comment by nkalupahana** [comment]
@mahen23 You can schedule 5 separate notifications -- one for each weekday you want the notification to be on.

**Comment by mahen23** [comment]
> @mahen23 You can schedule 5 separate notifications -- one for each weekday you want the notification to be on.

If i set a notification to be triggered at 9am, if i left the minute blank, its never triggered: 

on: {weekday: 4, hour: 9 } => this will never be triggered, be it 9:00 or 09:10 or 09:59
on: {weekday: 4, hour: 9, minute: 4 } => this will be triggered at only 09:04. 

is there a way i can configure notification to be triggered at any time from 09:00 to 09:59 ?

**Pull request merged**
