### PR TITLE
bugfix(Push notification) Fix register() due to FirebaseInstanceId deprecated

### PR DESCRIPTION
**Pull request by PierreNansot**
PushNotifications.register()  fail with com.google.firebase:firebase-messaging > 21.0.0 or com.google.firebase:firebase-bom > 28.0.0

See https://firebase.google.com/docs/reference/android/com/google/firebase/iid/FirebaseInstanceId

With fresh setup using @capacitor v3 and current version of firebase, it's essential to update this plugin.
Otherwise, it's useless and crash the app.

### CODE REVIEW

**Comment by jad18** [comment]
My team is looking to launch a product this week using 3.0.0, and we're having this same crash issue on Android when calling `PushNotifications.register()`. Could you please merge this when you get the chance? Thanks!

**Comment by PierreNansot** [comment]
Come on guys, it's been almost 2 weeks ! 
Everyday a marketing email in my inbox from you celebrating capacitor 3.0
But one of the main plugin doesn't even work!

**Comment by FabianMeul** [comment]
I can confirm this works.

A merge would be great! :-)

**Comment by gvcambraia** [comment]
hello @PierreNansot, thanks for your PR.
I'm experiencing the same issue, but when I try to apply your fix, I get the following error
`Cannot resolve method 'getToken' in 'FirebaseMessaging'`
Any ides on how to fix it?
Cheers

**Comment by jprinsloo** [comment]
I would also appreciate it if this PR could be merged as soon as possible.

**Comment by danielehrhardt** [comment]
This should be merged now.

**Review by danielehrhardt — APPROVED** [review]

**Comment by andreagobetti** [comment]
Any news? 😬

**Comment by warrendodsworth** [comment]
I would also appreciate it if this PR could be merged as soon as possible.

**Comment by gvcambraia** [comment]
This PR should be merged.
I can confirm that the fix on the registration method works as expected.

**Comment by stewones** [comment]
workaround while they merge this PR

```sh
npm install --save github:stewones/capacitor-push-notifications
npx cap sync android
```

**Comment by J4si3k** [comment]
please also fix it for Capacitor 2 version. On newest 2.5.0 it is not working, also crash app.

**Comment by taurix** [comment]
any update when this will be merged?

**Comment by daniel-zero** [comment]
I can also confirm this pr resolves the errors when upgrading the fcm SDK to the latest version >27.0

**Review by daniel-zero — APPROVED** [review]

**Comment by danielehrhardt** [comment]
What do i need to do that my app does not crash?

**Pull request closed without merging**
